version: "3.9"

## networks section
networks:
  development:
    driver: bridge

## volumes section
# volumes:

## services section
services:
  devcontainer:
    container_name: devcontainer
    image: "<your image>"
    volumes:
      - ../:/workspace:delegated
      - ~/.ssh:/root/.ssh-localhost:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/sh -c "while sleep 1000; do :; done"
